-- PROJETO SMARTCOFFE VANESSA
CREATE DATABASE SMARTCOFFE_VANESSA;

USE SMARTCOFFE_VANESSA;

CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (32),
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15),
EMAIL VARCHAR(20) ,
DATA_NASCIMENTO DATE
);

CREATE TABLE PEDIDOS (
ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
DATA_HORA TIMESTAMP,
STATUS_PEDIDO,
TIPO_AMBIENTE,
VALOR_TOTAL,
OBSERVACOES
);

CREATE TABLE PRODUTOS (
ID_PRODUTOS INT AUTO_INCREMENT PRIMARY KEY,
NOME_PRODUTO,
PRECO_UNITARIO,
TAMANHO_VOLUME,
DESCRICAO,
DISPONIVEL
);

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NOME_CATEGORIA,
DESCRICAO,
SETOR_PREPARO,
EXIBIR_MENU,
ORDEM_EXIBICAO
);

CREATE TABLE ESTOQUES (
ID_ESTOQUES INT AUTO_INCREMENT PRIMARY KEY,
NOME_INSUMO,
QUANTIDADE_ATUAL,
UNIDADE_MEDIDA,
ESTOQUE_MINIMO,
DATA_VALIDADE
);

CREATE TABLE FORNECEDOR (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
RAZAO_SOCIAL,
NOME_FANTASIA,
CNPJ,
TELEFONE_CONTATOS,
EMAIL_VENDAS
);

CREATE TABLE FUNCIONARIO (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO,
CARGO,
CPF,
TURNO,
DATA_ADMISSAO
);

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
FORMA_PAGAMENTO,
VALOR_PAGO,
DATA_PAGAMENTO,
STATUS_TRANSACAO,
CODIGO_AUTORIZACAO
);

CREATE TABLE DELIVERY(
ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
ENDERECO_ENTREGA,
TAXA_ENTREGA,
NOME_FORNCEDOR,
STATUS_ENTREGA,
TEMPO_ESTIMADO);

CREATE TABLE PROGRAMA_FIDELIDADE (
ID_PROGRAMAFIDELIDADE INT AUTO_INCREMENT PRIMARY KEY,
SALDO_PONTOS,
NIVEL_CLIENTE,
TOTAL_ACUMULADO,
DATA_ULTIMO_RESGATE,
CASHBACK_DISPONIVEL);