-- COMANDO PARA CRIAR BD
-- 1
CREATE DATABASE IF NOT EXISTS CLINICA_MEDICA_VANESSA;

-- ATIVAR O BD
-- 2
USE CLINICA_MEDICA_VANESSA;

-- TABELAS
-- 3
CREATE TABLE IF NOT EXISTS RECEPCAO (
ID_RECEPCAO INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE VARCHAR(15),
_FUNCIONAMENTO_HORARIO VARCHAR(5),
LOCALIDADE VARCHAR(20) NOT NULL, 
AREA VARCHAR(25) NOT NULL,
ATENDIMENTO VARCHAR(35),
CONVENIO ENUM ('SIM','NÃO') DEFAULT 'SIM',
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO_RECEPCIONISTA (
ID_RECEPCIONISTA INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
REGISTRO_CLIENTE VARCHAR(40) NOT NULL,
TURNO VARCHAR(5) NOT NULL,
AGENDAMENTO TIMESTAMP,
EMAIL VARCHAR(20) NOT NULL UNIQUE,
FORMA_PAGAMENTO ENUM ('CRÉDITO','DÉBITO','PIX') DEFAULT 'CRÉDITO',
PRECO DECIMAL(5,2) DEFAULT 0.00
);

CREATE TABLE CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME VARCHAR(40) NOT NULL,
DATA_NASCIMENTO DATE,
TELEFONE VARCHAR(15),
CADASTRO TIMESTAMP,
EMAIL VARCHAR(20) 
);

CREATE TABLE AMBIENTES (
ID_AMBIENTES INT AUTO_INCREMENT PRIMARY KEY,
TIPO_AMBIENTE VARCHAR(35) NOT NULL,
NOME_SALA VARCHAR(35) NOT NULL,
CAPACIDADE_FUNCIONARIOS INT,
STATUS_AMBIENTE VARCHAR(7) DEFAULT "Ativo",
DESCRICAO VARCHAR(50) 
);

CREATE TABLE SERVICOS_EXTRAS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
FUNCIONARIOS INT,
TIPO_SALA VARCHAR(35) NOT NULL,
DISPONIBILIDADE VARCHAR(7) DEFAULT "Ativo",
VALOR VARCHAR(7) DEFAULT "Credito",
TIPO_SEVICOS VARCHAR(35) 
);

-- VISUALIZAR TABELAS
-- 4
SHOW TABLES;

-- 5 EM CASO DE NECESSIDADE OU CORREÇÃO
-- APAGAR BD
-- NÃO EXECUTAR SE NÃO QUISER APAGAR O BANCO
-- DROP DATABASE CLINICA_MEDICA_VANESSA;

-- APAGAR TABELAS
-- NÃO EXECUTAR SE NÃO QUISER APAGAR A TABELA
-- DROP TABLE RECEPCAO;

-- COMANDOS PARA EXECUTAR CASO TENHA ESQUECIDO ALGO NAS TABELAS

-- INSERIR CAMPOS
ALTER TABLE RECEPCAO ADD EMAIL VARCHAR(100);

-- ALTERAR TIPO DE DADOS
ALTER TABLE RECEPCAO MODIFY TELEFONE INT;
ALTER TABLE RECEPCAO MODIFY COLUMN TELEFONE VARCHAR(15);
ALTER TABLE CLIENTES MODIFY COLUMN CADASTRO ENUM ('SIM','NÃO') DEFAULT 'SIM';

-- APAGAR COLUNA OU ATRIBUTO
ALTER TABLE ALUNOS DROP COLUMN TELEFONE;

-- RENOMEAR TABELAS
RENAME TABLE RECEPCAO TO ATENDIMENTO_RECEPCAO;

-- APAGAR DADOS DE UMA TABELA
TRUNCATE TABLE FUNCIONARIO_RECEPCIONISTA;

-- INSERIR DADOS NA TABELA
INSERT INTO RECEPCAO (ID_RECEPCAO, TELEFONE, _FUNCIONAMENTO_HORARIO, LOCALIDADE, AREA, ATENDIMENTO, CONVENIO, DATA_CADASTRO)
VALUES (1, '19987148531', '8:30', 'Recepção', 'Limeira-SP', 'Presencial', 'SIM', '2026-08-20 8:30');

INSERT INTO FUNCIONARIO_RECEPCIONISTA (ID_RECEPCIONISTA, NOME, REGISTRO_CLIENTE, TURNO, AGENDAMENTO, EMAIL, FORMA_PAGAMENTO, PRECO)
VALUES (1, 'Maria Silva', 'CLI001', '08:00', '2026-08-20 08:00:00', 'maria@email.com', 'PIX', 25.00);

-- SELECT * FROM RECEPCAO
-- SELECT * FROM FUNCIONARIO_RECEPCIONISTA;