CREATE DATABASE OFICINA_VANESSA;

USE OFICINA_VANESSA;

CREATE TABLE CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(32),
CPF VARCHAR(14)NOT NULL,
TELEFONE VARCHAR(8),
AUTOMOVEL ENUM ('CARRO','MOTO') DEFAULT 'CARRO',
EMAIL VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE VEICULOS (
ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
MODELO VARCHAR(15),
PLACA VARCHAR(15),
COR VARCHAR(20),
ANO DATE,
TIPO_COMBUSTIVEL VARCHAR(25)
);

CREATE TABLE MARCAS (
ID_MARCAS INT AUTO_INCREMENT PRIMARY KEY,
FORMATO VARCHAR(35),
ANO DATE,
COR VARCHAR(25),
VERSAO VARCHAR(15),
COMBUSTIVEL_TIPO VARCHAR(20)
);

CREATE TABLE MODELOS (
ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (35),
CATEGORIA VARCHAR(60),
PORTE ENUM ('COMPACTO','MEDIO','GRANDE') DEFAULT 'MEDIO',
DESCRICAO VARCHAR(100),
AGENCIA VARCHAR(25)
);

CREATE TABLE FUNCIONARIO (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
DADOS_CLIENTES VARCHAR(100),
DADOS_AUTOMOVEL VARCHAR(100),
TIPO_FUNCIONARIO VARCHAR(65),
TURNO ENUM ('MANHA','TARDE','NOITE') DEFAULT 'MANHA',
TELEFONE VARCHAR(14)
);

CREATE TABLE SERVICOS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
TIPO_FUNCIONARIOS VARCHAR(35),
DESCRICAO_PROBLEM VARCHAR(100),
PERIODICOS VARCHAR(100),
TEMPO TIMESTAMP,
PORTFOLIO VARCHAR(100)
);

CREATE TABLE PECAS (
ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
CODIGO INT,
NOME VARCHAR(35),
PRECO FLOAT,
ESTOQUE INT,
FABRICANTE VARCHAR(25)
);

CREATE TABLE ORDENS_DE_SERVICOS (
ID_ORDENSSERVICOS INT AUTO_INCREMENT PRIMARY KEY,
CLIENTES_DADOS VARCHAR(60),
DADOS_VEICULO VARCHAR(60),
DESCRICAO_PROBLEMA VARCHAR(100),
ORCAMENTO INT,
ASSINATURA_CLIENTE ENUM ('SIM','NÃO') DEFAULT 'SIM'
);

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
FORMA_PAGAMENTO ENUM ('CRÉDITO','DÉBITO','PIX') DEFAULT 'CRÉDITO',
VALOR_PAGO FLOAT,
DATA_PAGAMENTO DATE,
STATUS_TRANSACAO VARCHAR(20),
COMPROVANTE VARCHAR(100)
);

CREATE TABLE FORNECEDORES (
ID_FORNECEDORES INT AUTO_INCREMENT PRIMARY KEY,
RAZAO_SOCIAL VARCHAR(23),
CNPJ INT,
TELEFONE_CONTATOS VARCHAR(14),
EMAIL_VENDAS VARCHAR(25)NOT NULL UNIQUE,
INSCRICAO_ESTADUAL VARCHAR(10)
);

RENAME TABLE CLIENTES TO CLIENTE;
