-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE CLINICA_MEDICA;
CREATE DATABASE CLINICA_MEDICA01;

-- COMANDO PARA APAGAR BANCO DE DADOS
DROP DATABASE clinica_medica01;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE CLINICA_MEDICA;

-- COMANDO PARA CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME VARCHAR(40) NOT NULL,
DATA_NASCIMENTO DATE,
TELEFONE VARCHAR(15),
CADASTRO TIMESTAMP,
EMAIL VARCHAR(20) 
);

CREATE TABLE RECEPCAO (
ID_RECEPCAO INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE VARCHAR(15),
_FUNCIONAMENTO_HORARIO VARCHAR(5),
LOCALIDADE VARCHAR(20) NOT NULL, 
AREA VARCHAR(25) NOT NULL,
ATENDIMENTO VARCHAR(35) 
);

CREATE TABLE FUNCIONARIO_RECEPCIONISTA (
ID_RECEPCIONISTA INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
REGISTRO_CLIENTE VARCHAR(40) NOT NULL,
TURNO VARCHAR(5) NOT NULL,
AGENDAMENTO TIMESTAMP,
EMAIL VARCHAR(20) NOT NULL UNIQUE 
);

CREATE TABLE AMBIENTES (
ID_AMBIENTES INT AUTO_INCREMENT PRIMARY KEY,
TIPO_AMBIENTE VARCHAR(35) NOT NULL,
NOME_SALA VARCHAR(35) NOT NULL,
CAPACIDADE_FUNCIONARIOS INT,
STATUS_AMBIENTE VARCHAR(7) DEFAULT "Ativo",
DESCRICAO VARCHAR(50) 
);

CREATE TABLE SERVICOS_EXTRAS (
ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
FUNCIONARIOS INT,
TIPO_SALA VARCHAR(35) NOT NULL,
DISPONIBILIDADE VARCHAR(7) DEFAULT "Ativo",
VALOR VARCHAR(7) DEFAULT "Credito",
TIPO_SEVICOS VARCHAR(35) 
);